// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fairnode/fairnode.proto

package fairnode

import (
	context "context"
	fmt "fmt"
	common "github.com/anduschain/go-anduschain/protos/common"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("fairnode/fairnode.proto", fileDescriptor_be599e5d5fddfca2) }

var fileDescriptor_be599e5d5fddfca2 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x86, 0x73, 0xa4, 0xea, 0x88, 0x9a, 0x72, 0xa9, 0x23, 0x5a, 0xc9, 0xec, 0xb2, 0x27, 0x41,
	0x2d, 0x08, 0xb6, 0xb4, 0x14, 0x81, 0x04, 0xa2, 0x4a, 0x25, 0x16, 0x88, 0x8d, 0x9b, 0x4e, 0x53,
	0x8b, 0xc4, 0x4e, 0x6d, 0x07, 0xa9, 0xef, 0xc6, 0xc3, 0xa1, 0x5c, 0x9c, 0x98, 0x05, 0x5d, 0x25,
	0xf3, 0xfd, 0x33, 0xff, 0x78, 0x32, 0x31, 0x1a, 0xae, 0x29, 0x93, 0x5c, 0xac, 0x20, 0x30, 0x2f,
	0x7e, 0x26, 0x85, 0x16, 0xf8, 0xc0, 0xc4, 0xc4, 0x8d, 0x44, 0x9a, 0x0a, 0x1e, 0x54, 0x8f, 0x4a,
	0x26, 0xe7, 0xb1, 0x10, 0x71, 0x02, 0x41, 0x19, 0x2d, 0xf3, 0x75, 0x00, 0x69, 0xa6, 0x77, 0x95,
	0x38, 0xfa, 0xee, 0xa0, 0x93, 0x87, 0xba, 0x7c, 0x01, 0xf2, 0x8b, 0x45, 0x80, 0x6f, 0x51, 0xf7,
	0x11, 0xa8, 0xd4, 0x13, 0xa0, 0x1a, 0xf7, 0xfd, 0xda, 0xac, 0x41, 0x64, 0xe0, 0x57, 0x8e, 0xbe,
	0x71, 0xf4, 0x67, 0x85, 0xa3, 0xe7, 0xe0, 0x2b, 0xd4, 0x0b, 0x61, 0x9b, 0x83, 0xd2, 0xaf, 0x3a,
	0x93, 0x1c, 0x9f, 0x9a, 0xe2, 0x10, 0xb6, 0x25, 0x21, 0x16, 0x51, 0x25, 0xf1, 0x1c, 0x7c, 0x8f,
	0xfa, 0x73, 0x29, 0x22, 0x50, 0x6a, 0x2a, 0xb8, 0x96, 0x22, 0x49, 0x40, 0x62, 0xd7, 0x24, 0xce,
	0xa9, 0xd4, 0x2c, 0x62, 0x19, 0xd5, 0x40, 0x06, 0x0d, 0xac, 0xf2, 0x5f, 0x40, 0x29, 0x1a, 0x83,
	0xe7, 0x5c, 0xfe, 0xc3, 0x37, 0xe8, 0xa8, 0xee, 0xfd, 0x0c, 0x34, 0xce, 0xa1, 0x3d, 0x79, 0x08,
	0xdb, 0x0a, 0x11, 0x0b, 0xa9, 0x0a, 0x79, 0x0e, 0xf6, 0x51, 0xe7, 0x4d, 0x68, 0xc0, 0x3d, 0x23,
	0x16, 0xd1, 0x9e, 0x21, 0xa7, 0xa8, 0x5f, 0x37, 0x2a, 0x12, 0x43, 0x50, 0x79, 0xa2, 0xf1, 0x99,
	0xd5, 0xac, 0xc5, 0xc4, 0xc2, 0xaa, 0xc5, 0x9e, 0x83, 0xef, 0xd0, 0xe1, 0x02, 0x68, 0x32, 0x15,
	0x7c, 0xcd, 0x64, 0x8a, 0x07, 0x56, 0x79, 0xcd, 0x0a, 0x99, 0x58, 0x5c, 0x59, 0xbc, 0x1e, 0xb8,
	0xbb, 0x00, 0xbe, 0x9a, 0x24, 0x22, 0xfa, 0xfc, 0xf5, 0xa5, 0x4b, 0xb2, 0x67, 0x80, 0x27, 0xe4,
	0xd6, 0x03, 0x34, 0x9b, 0x67, 0x31, 0xc7, 0x43, 0xcb, 0xc2, 0x16, 0x88, 0x25, 0x28, 0x5b, 0xf0,
	0x9c, 0xd1, 0x07, 0x72, 0x1b, 0xb2, 0xe3, 0x91, 0xf9, 0x83, 0x66, 0xe8, 0xb8, 0x08, 0xad, 0x75,
	0xfe, 0x71, 0x9a, 0xd6, 0xdb, 0xd8, 0x58, 0x2b, 0x9d, 0x5c, 0xbf, 0x8f, 0x63, 0xa6, 0x37, 0xf9,
	0xb2, 0x48, 0x0a, 0x28, 0x5f, 0xe5, 0x2a, 0xda, 0x50, 0xc6, 0x83, 0x58, 0x5c, 0x58, 0x51, 0x69,
	0xa9, 0x9a, 0x5b, 0xb1, 0xfc, 0x5f, 0x82, 0xf1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0xc4,
	0xb0, 0x5a, 0x31, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FairnodeServiceClient is the client API for FairnodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FairnodeServiceClient interface {
	HeartBeat(ctx context.Context, in *common.HeartBeat, opts ...grpc.CallOption) (*empty.Empty, error)
	RequestOtprn(ctx context.Context, in *common.ReqOtprn, opts ...grpc.CallOption) (*common.ResOtprn, error)
	ProcessController(ctx context.Context, in *common.Participate, opts ...grpc.CallOption) (FairnodeService_ProcessControllerClient, error)
	RequestLeague(ctx context.Context, in *common.ReqLeague, opts ...grpc.CallOption) (*common.ResLeague, error)
	Vote(ctx context.Context, in *common.Vote, opts ...grpc.CallOption) (*empty.Empty, error)
	RequestVoteResult(ctx context.Context, in *common.ReqVoteResult, opts ...grpc.CallOption) (*common.ResVoteResult, error)
	SealConfirm(ctx context.Context, in *common.ReqConfirmSeal, opts ...grpc.CallOption) (FairnodeService_SealConfirmClient, error)
	SendBlock(ctx context.Context, in *common.ReqBlock, opts ...grpc.CallOption) (*empty.Empty, error)
	RequestFairnodeSign(ctx context.Context, in *common.ReqFairnodeSign, opts ...grpc.CallOption) (*common.ResFairnodeSign, error)
}

type fairnodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewFairnodeServiceClient(cc *grpc.ClientConn) FairnodeServiceClient {
	return &fairnodeServiceClient{cc}
}

func (c *fairnodeServiceClient) HeartBeat(ctx context.Context, in *common.HeartBeat, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/fairnode.FairnodeService/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fairnodeServiceClient) RequestOtprn(ctx context.Context, in *common.ReqOtprn, opts ...grpc.CallOption) (*common.ResOtprn, error) {
	out := new(common.ResOtprn)
	err := c.cc.Invoke(ctx, "/fairnode.FairnodeService/RequestOtprn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fairnodeServiceClient) ProcessController(ctx context.Context, in *common.Participate, opts ...grpc.CallOption) (FairnodeService_ProcessControllerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FairnodeService_serviceDesc.Streams[0], "/fairnode.FairnodeService/ProcessController", opts...)
	if err != nil {
		return nil, err
	}
	x := &fairnodeServiceProcessControllerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FairnodeService_ProcessControllerClient interface {
	Recv() (*common.ProcessMessage, error)
	grpc.ClientStream
}

type fairnodeServiceProcessControllerClient struct {
	grpc.ClientStream
}

func (x *fairnodeServiceProcessControllerClient) Recv() (*common.ProcessMessage, error) {
	m := new(common.ProcessMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fairnodeServiceClient) RequestLeague(ctx context.Context, in *common.ReqLeague, opts ...grpc.CallOption) (*common.ResLeague, error) {
	out := new(common.ResLeague)
	err := c.cc.Invoke(ctx, "/fairnode.FairnodeService/RequestLeague", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fairnodeServiceClient) Vote(ctx context.Context, in *common.Vote, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/fairnode.FairnodeService/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fairnodeServiceClient) RequestVoteResult(ctx context.Context, in *common.ReqVoteResult, opts ...grpc.CallOption) (*common.ResVoteResult, error) {
	out := new(common.ResVoteResult)
	err := c.cc.Invoke(ctx, "/fairnode.FairnodeService/RequestVoteResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fairnodeServiceClient) SealConfirm(ctx context.Context, in *common.ReqConfirmSeal, opts ...grpc.CallOption) (FairnodeService_SealConfirmClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FairnodeService_serviceDesc.Streams[1], "/fairnode.FairnodeService/SealConfirm", opts...)
	if err != nil {
		return nil, err
	}
	x := &fairnodeServiceSealConfirmClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FairnodeService_SealConfirmClient interface {
	Recv() (*common.ResConfirmSeal, error)
	grpc.ClientStream
}

type fairnodeServiceSealConfirmClient struct {
	grpc.ClientStream
}

func (x *fairnodeServiceSealConfirmClient) Recv() (*common.ResConfirmSeal, error) {
	m := new(common.ResConfirmSeal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fairnodeServiceClient) SendBlock(ctx context.Context, in *common.ReqBlock, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/fairnode.FairnodeService/SendBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fairnodeServiceClient) RequestFairnodeSign(ctx context.Context, in *common.ReqFairnodeSign, opts ...grpc.CallOption) (*common.ResFairnodeSign, error) {
	out := new(common.ResFairnodeSign)
	err := c.cc.Invoke(ctx, "/fairnode.FairnodeService/RequestFairnodeSign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FairnodeServiceServer is the server API for FairnodeService service.
type FairnodeServiceServer interface {
	HeartBeat(context.Context, *common.HeartBeat) (*empty.Empty, error)
	RequestOtprn(context.Context, *common.ReqOtprn) (*common.ResOtprn, error)
	ProcessController(*common.Participate, FairnodeService_ProcessControllerServer) error
	RequestLeague(context.Context, *common.ReqLeague) (*common.ResLeague, error)
	Vote(context.Context, *common.Vote) (*empty.Empty, error)
	RequestVoteResult(context.Context, *common.ReqVoteResult) (*common.ResVoteResult, error)
	SealConfirm(*common.ReqConfirmSeal, FairnodeService_SealConfirmServer) error
	SendBlock(context.Context, *common.ReqBlock) (*empty.Empty, error)
	RequestFairnodeSign(context.Context, *common.ReqFairnodeSign) (*common.ResFairnodeSign, error)
}

// UnimplementedFairnodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFairnodeServiceServer struct {
}

func (*UnimplementedFairnodeServiceServer) HeartBeat(ctx context.Context, req *common.HeartBeat) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (*UnimplementedFairnodeServiceServer) RequestOtprn(ctx context.Context, req *common.ReqOtprn) (*common.ResOtprn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestOtprn not implemented")
}
func (*UnimplementedFairnodeServiceServer) ProcessController(req *common.Participate, srv FairnodeService_ProcessControllerServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessController not implemented")
}
func (*UnimplementedFairnodeServiceServer) RequestLeague(ctx context.Context, req *common.ReqLeague) (*common.ResLeague, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestLeague not implemented")
}
func (*UnimplementedFairnodeServiceServer) Vote(ctx context.Context, req *common.Vote) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}
func (*UnimplementedFairnodeServiceServer) RequestVoteResult(ctx context.Context, req *common.ReqVoteResult) (*common.ResVoteResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVoteResult not implemented")
}
func (*UnimplementedFairnodeServiceServer) SealConfirm(req *common.ReqConfirmSeal, srv FairnodeService_SealConfirmServer) error {
	return status.Errorf(codes.Unimplemented, "method SealConfirm not implemented")
}
func (*UnimplementedFairnodeServiceServer) SendBlock(ctx context.Context, req *common.ReqBlock) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBlock not implemented")
}
func (*UnimplementedFairnodeServiceServer) RequestFairnodeSign(ctx context.Context, req *common.ReqFairnodeSign) (*common.ResFairnodeSign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestFairnodeSign not implemented")
}

func RegisterFairnodeServiceServer(s *grpc.Server, srv FairnodeServiceServer) {
	s.RegisterService(&_FairnodeService_serviceDesc, srv)
}

func _FairnodeService_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.HeartBeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FairnodeServiceServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairnode.FairnodeService/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FairnodeServiceServer).HeartBeat(ctx, req.(*common.HeartBeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _FairnodeService_RequestOtprn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ReqOtprn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FairnodeServiceServer).RequestOtprn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairnode.FairnodeService/RequestOtprn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FairnodeServiceServer).RequestOtprn(ctx, req.(*common.ReqOtprn))
	}
	return interceptor(ctx, in, info, handler)
}

func _FairnodeService_ProcessController_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.Participate)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FairnodeServiceServer).ProcessController(m, &fairnodeServiceProcessControllerServer{stream})
}

type FairnodeService_ProcessControllerServer interface {
	Send(*common.ProcessMessage) error
	grpc.ServerStream
}

type fairnodeServiceProcessControllerServer struct {
	grpc.ServerStream
}

func (x *fairnodeServiceProcessControllerServer) Send(m *common.ProcessMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _FairnodeService_RequestLeague_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ReqLeague)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FairnodeServiceServer).RequestLeague(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairnode.FairnodeService/RequestLeague",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FairnodeServiceServer).RequestLeague(ctx, req.(*common.ReqLeague))
	}
	return interceptor(ctx, in, info, handler)
}

func _FairnodeService_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Vote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FairnodeServiceServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairnode.FairnodeService/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FairnodeServiceServer).Vote(ctx, req.(*common.Vote))
	}
	return interceptor(ctx, in, info, handler)
}

func _FairnodeService_RequestVoteResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ReqVoteResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FairnodeServiceServer).RequestVoteResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairnode.FairnodeService/RequestVoteResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FairnodeServiceServer).RequestVoteResult(ctx, req.(*common.ReqVoteResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _FairnodeService_SealConfirm_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.ReqConfirmSeal)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FairnodeServiceServer).SealConfirm(m, &fairnodeServiceSealConfirmServer{stream})
}

type FairnodeService_SealConfirmServer interface {
	Send(*common.ResConfirmSeal) error
	grpc.ServerStream
}

type fairnodeServiceSealConfirmServer struct {
	grpc.ServerStream
}

func (x *fairnodeServiceSealConfirmServer) Send(m *common.ResConfirmSeal) error {
	return x.ServerStream.SendMsg(m)
}

func _FairnodeService_SendBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ReqBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FairnodeServiceServer).SendBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairnode.FairnodeService/SendBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FairnodeServiceServer).SendBlock(ctx, req.(*common.ReqBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _FairnodeService_RequestFairnodeSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ReqFairnodeSign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FairnodeServiceServer).RequestFairnodeSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairnode.FairnodeService/RequestFairnodeSign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FairnodeServiceServer).RequestFairnodeSign(ctx, req.(*common.ReqFairnodeSign))
	}
	return interceptor(ctx, in, info, handler)
}

var _FairnodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fairnode.FairnodeService",
	HandlerType: (*FairnodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartBeat",
			Handler:    _FairnodeService_HeartBeat_Handler,
		},
		{
			MethodName: "RequestOtprn",
			Handler:    _FairnodeService_RequestOtprn_Handler,
		},
		{
			MethodName: "RequestLeague",
			Handler:    _FairnodeService_RequestLeague_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _FairnodeService_Vote_Handler,
		},
		{
			MethodName: "RequestVoteResult",
			Handler:    _FairnodeService_RequestVoteResult_Handler,
		},
		{
			MethodName: "SendBlock",
			Handler:    _FairnodeService_SendBlock_Handler,
		},
		{
			MethodName: "RequestFairnodeSign",
			Handler:    _FairnodeService_RequestFairnodeSign_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessController",
			Handler:       _FairnodeService_ProcessController_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SealConfirm",
			Handler:       _FairnodeService_SealConfirm_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fairnode/fairnode.proto",
}

// FairnodeSyncServiceClient is the client API for FairnodeSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FairnodeSyncServiceClient interface {
	SyncController(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (FairnodeSyncService_SyncControllerClient, error)
}

type fairnodeSyncServiceClient struct {
	cc *grpc.ClientConn
}

func NewFairnodeSyncServiceClient(cc *grpc.ClientConn) FairnodeSyncServiceClient {
	return &fairnodeSyncServiceClient{cc}
}

func (c *fairnodeSyncServiceClient) SyncController(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (FairnodeSyncService_SyncControllerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FairnodeSyncService_serviceDesc.Streams[0], "/fairnode.FairnodeSyncService/SyncController", opts...)
	if err != nil {
		return nil, err
	}
	x := &fairnodeSyncServiceSyncControllerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FairnodeSyncService_SyncControllerClient interface {
	Recv() (*common.FairnodeMessage, error)
	grpc.ClientStream
}

type fairnodeSyncServiceSyncControllerClient struct {
	grpc.ClientStream
}

func (x *fairnodeSyncServiceSyncControllerClient) Recv() (*common.FairnodeMessage, error) {
	m := new(common.FairnodeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FairnodeSyncServiceServer is the server API for FairnodeSyncService service.
type FairnodeSyncServiceServer interface {
	SyncController(*empty.Empty, FairnodeSyncService_SyncControllerServer) error
}

// UnimplementedFairnodeSyncServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFairnodeSyncServiceServer struct {
}

func (*UnimplementedFairnodeSyncServiceServer) SyncController(req *empty.Empty, srv FairnodeSyncService_SyncControllerServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncController not implemented")
}

func RegisterFairnodeSyncServiceServer(s *grpc.Server, srv FairnodeSyncServiceServer) {
	s.RegisterService(&_FairnodeSyncService_serviceDesc, srv)
}

func _FairnodeSyncService_SyncController_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FairnodeSyncServiceServer).SyncController(m, &fairnodeSyncServiceSyncControllerServer{stream})
}

type FairnodeSyncService_SyncControllerServer interface {
	Send(*common.FairnodeMessage) error
	grpc.ServerStream
}

type fairnodeSyncServiceSyncControllerServer struct {
	grpc.ServerStream
}

func (x *fairnodeSyncServiceSyncControllerServer) Send(m *common.FairnodeMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _FairnodeSyncService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fairnode.FairnodeSyncService",
	HandlerType: (*FairnodeSyncServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncController",
			Handler:       _FairnodeSyncService_SyncController_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fairnode/fairnode.proto",
}
