// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/anduschain/go/src/github.com/anduschain/go-anduschain/fairnode/mock_fairnode/../../protos/fairnode/fairnode.pb.go

// Package mock_fairnode is a generated GoMock package.
package mock_fairnode
