// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/hakuna/go/src/github.com/anduschain/go-anduschain/protos/fairnode/fairnode.pb.go

// Package mock_fairnode is a generated GoMock package.
package mock_fairnode

import (
	context "context"
	common "github.com/anduschain/go-anduschain/protos/common"
	fairnode "github.com/anduschain/go-anduschain/protos/fairnode"
	gomock "github.com/golang/mock/gomock"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	reflect "reflect"
)

// MockFairnodeServiceClient is a mock of FairnodeServiceClient interface
type MockFairnodeServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockFairnodeServiceClientMockRecorder
}

// MockFairnodeServiceClientMockRecorder is the mock recorder for MockFairnodeServiceClient
type MockFairnodeServiceClientMockRecorder struct {
	mock *MockFairnodeServiceClient
}

// NewMockFairnodeServiceClient creates a new mock instance
func NewMockFairnodeServiceClient(ctrl *gomock.Controller) *MockFairnodeServiceClient {
	mock := &MockFairnodeServiceClient{ctrl: ctrl}
	mock.recorder = &MockFairnodeServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFairnodeServiceClient) EXPECT() *MockFairnodeServiceClientMockRecorder {
	return m.recorder
}

// HeartBeat mocks base method
func (m *MockFairnodeServiceClient) HeartBeat(ctx context.Context, in *common.HeartBeat, opts ...grpc.CallOption) (*empty.Empty, error) {
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HeartBeat", varargs...)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeartBeat indicates an expected call of HeartBeat
func (mr *MockFairnodeServiceClientMockRecorder) HeartBeat(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeartBeat", reflect.TypeOf((*MockFairnodeServiceClient)(nil).HeartBeat), varargs...)
}

// RequestOtprn mocks base method
func (m *MockFairnodeServiceClient) RequestOtprn(ctx context.Context, in *common.ReqOtprn, opts ...grpc.CallOption) (*common.ResOtprn, error) {
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RequestOtprn", varargs...)
	ret0, _ := ret[0].(*common.ResOtprn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestOtprn indicates an expected call of RequestOtprn
func (mr *MockFairnodeServiceClientMockRecorder) RequestOtprn(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestOtprn", reflect.TypeOf((*MockFairnodeServiceClient)(nil).RequestOtprn), varargs...)
}

// ProcessController mocks base method
func (m *MockFairnodeServiceClient) ProcessController(ctx context.Context, in *common.Participate, opts ...grpc.CallOption) (fairnode.FairnodeService_ProcessControllerClient, error) {
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProcessController", varargs...)
	ret0, _ := ret[0].(fairnode.FairnodeService_ProcessControllerClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessController indicates an expected call of ProcessController
func (mr *MockFairnodeServiceClientMockRecorder) ProcessController(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessController", reflect.TypeOf((*MockFairnodeServiceClient)(nil).ProcessController), varargs...)
}

// Vote mocks base method
func (m *MockFairnodeServiceClient) Vote(ctx context.Context, in *common.Vote, opts ...grpc.CallOption) (*empty.Empty, error) {
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Vote", varargs...)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Vote indicates an expected call of Vote
func (mr *MockFairnodeServiceClientMockRecorder) Vote(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vote", reflect.TypeOf((*MockFairnodeServiceClient)(nil).Vote), varargs...)
}

// RequestVoteResult mocks base method
func (m *MockFairnodeServiceClient) RequestVoteResult(ctx context.Context, in *common.ReqVoteResult, opts ...grpc.CallOption) (*common.ResVoteResult, error) {
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RequestVoteResult", varargs...)
	ret0, _ := ret[0].(*common.ResVoteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestVoteResult indicates an expected call of RequestVoteResult
func (mr *MockFairnodeServiceClientMockRecorder) RequestVoteResult(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestVoteResult", reflect.TypeOf((*MockFairnodeServiceClient)(nil).RequestVoteResult), varargs...)
}

// SealConfirm mocks base method
func (m *MockFairnodeServiceClient) SealConfirm(ctx context.Context, in *common.ReqConfirmSeal, opts ...grpc.CallOption) (fairnode.FairnodeService_SealConfirmClient, error) {
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SealConfirm", varargs...)
	ret0, _ := ret[0].(fairnode.FairnodeService_SealConfirmClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SealConfirm indicates an expected call of SealConfirm
func (mr *MockFairnodeServiceClientMockRecorder) SealConfirm(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SealConfirm", reflect.TypeOf((*MockFairnodeServiceClient)(nil).SealConfirm), varargs...)
}

// SendBlock mocks base method
func (m *MockFairnodeServiceClient) SendBlock(ctx context.Context, in *common.ReqBlock, opts ...grpc.CallOption) (*empty.Empty, error) {
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendBlock", varargs...)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendBlock indicates an expected call of SendBlock
func (mr *MockFairnodeServiceClientMockRecorder) SendBlock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBlock", reflect.TypeOf((*MockFairnodeServiceClient)(nil).SendBlock), varargs...)
}

// RequestFairnodeSign mocks base method
func (m *MockFairnodeServiceClient) RequestFairnodeSign(ctx context.Context, in *common.ReqFairnodeSign, opts ...grpc.CallOption) (*common.ResFairnodeSign, error) {
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RequestFairnodeSign", varargs...)
	ret0, _ := ret[0].(*common.ResFairnodeSign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestFairnodeSign indicates an expected call of RequestFairnodeSign
func (mr *MockFairnodeServiceClientMockRecorder) RequestFairnodeSign(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestFairnodeSign", reflect.TypeOf((*MockFairnodeServiceClient)(nil).RequestFairnodeSign), varargs...)
}

// MockFairnodeService_ProcessControllerClient is a mock of FairnodeService_ProcessControllerClient interface
type MockFairnodeService_ProcessControllerClient struct {
	ctrl     *gomock.Controller
	recorder *MockFairnodeService_ProcessControllerClientMockRecorder
}

// MockFairnodeService_ProcessControllerClientMockRecorder is the mock recorder for MockFairnodeService_ProcessControllerClient
type MockFairnodeService_ProcessControllerClientMockRecorder struct {
	mock *MockFairnodeService_ProcessControllerClient
}

// NewMockFairnodeService_ProcessControllerClient creates a new mock instance
func NewMockFairnodeService_ProcessControllerClient(ctrl *gomock.Controller) *MockFairnodeService_ProcessControllerClient {
	mock := &MockFairnodeService_ProcessControllerClient{ctrl: ctrl}
	mock.recorder = &MockFairnodeService_ProcessControllerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFairnodeService_ProcessControllerClient) EXPECT() *MockFairnodeService_ProcessControllerClientMockRecorder {
	return m.recorder
}

// Recv mocks base method
func (m *MockFairnodeService_ProcessControllerClient) Recv() (*common.ProcessMessage, error) {
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*common.ProcessMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockFairnodeService_ProcessControllerClientMockRecorder) Recv() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockFairnodeService_ProcessControllerClient)(nil).Recv))
}

// Header mocks base method
func (m *MockFairnodeService_ProcessControllerClient) Header() (metadata.MD, error) {
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header
func (mr *MockFairnodeService_ProcessControllerClientMockRecorder) Header() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockFairnodeService_ProcessControllerClient)(nil).Header))
}

// Trailer mocks base method
func (m *MockFairnodeService_ProcessControllerClient) Trailer() metadata.MD {
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer
func (mr *MockFairnodeService_ProcessControllerClientMockRecorder) Trailer() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockFairnodeService_ProcessControllerClient)(nil).Trailer))
}

// CloseSend mocks base method
func (m *MockFairnodeService_ProcessControllerClient) CloseSend() error {
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend
func (mr *MockFairnodeService_ProcessControllerClientMockRecorder) CloseSend() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockFairnodeService_ProcessControllerClient)(nil).CloseSend))
}

// Context mocks base method
func (m *MockFairnodeService_ProcessControllerClient) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockFairnodeService_ProcessControllerClientMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockFairnodeService_ProcessControllerClient)(nil).Context))
}

// SendMsg mocks base method
func (m_2 *MockFairnodeService_ProcessControllerClient) SendMsg(m interface{}) error {
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockFairnodeService_ProcessControllerClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockFairnodeService_ProcessControllerClient)(nil).SendMsg), m)
}

// RecvMsg mocks base method
func (m_2 *MockFairnodeService_ProcessControllerClient) RecvMsg(m interface{}) error {
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockFairnodeService_ProcessControllerClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockFairnodeService_ProcessControllerClient)(nil).RecvMsg), m)
}

// MockFairnodeService_SealConfirmClient is a mock of FairnodeService_SealConfirmClient interface
type MockFairnodeService_SealConfirmClient struct {
	ctrl     *gomock.Controller
	recorder *MockFairnodeService_SealConfirmClientMockRecorder
}

// MockFairnodeService_SealConfirmClientMockRecorder is the mock recorder for MockFairnodeService_SealConfirmClient
type MockFairnodeService_SealConfirmClientMockRecorder struct {
	mock *MockFairnodeService_SealConfirmClient
}

// NewMockFairnodeService_SealConfirmClient creates a new mock instance
func NewMockFairnodeService_SealConfirmClient(ctrl *gomock.Controller) *MockFairnodeService_SealConfirmClient {
	mock := &MockFairnodeService_SealConfirmClient{ctrl: ctrl}
	mock.recorder = &MockFairnodeService_SealConfirmClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFairnodeService_SealConfirmClient) EXPECT() *MockFairnodeService_SealConfirmClientMockRecorder {
	return m.recorder
}

// Recv mocks base method
func (m *MockFairnodeService_SealConfirmClient) Recv() (*common.ResConfirmSeal, error) {
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*common.ResConfirmSeal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockFairnodeService_SealConfirmClientMockRecorder) Recv() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockFairnodeService_SealConfirmClient)(nil).Recv))
}

// Header mocks base method
func (m *MockFairnodeService_SealConfirmClient) Header() (metadata.MD, error) {
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header
func (mr *MockFairnodeService_SealConfirmClientMockRecorder) Header() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockFairnodeService_SealConfirmClient)(nil).Header))
}

// Trailer mocks base method
func (m *MockFairnodeService_SealConfirmClient) Trailer() metadata.MD {
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer
func (mr *MockFairnodeService_SealConfirmClientMockRecorder) Trailer() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockFairnodeService_SealConfirmClient)(nil).Trailer))
}

// CloseSend mocks base method
func (m *MockFairnodeService_SealConfirmClient) CloseSend() error {
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend
func (mr *MockFairnodeService_SealConfirmClientMockRecorder) CloseSend() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockFairnodeService_SealConfirmClient)(nil).CloseSend))
}

// Context mocks base method
func (m *MockFairnodeService_SealConfirmClient) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockFairnodeService_SealConfirmClientMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockFairnodeService_SealConfirmClient)(nil).Context))
}

// SendMsg mocks base method
func (m_2 *MockFairnodeService_SealConfirmClient) SendMsg(m interface{}) error {
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockFairnodeService_SealConfirmClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockFairnodeService_SealConfirmClient)(nil).SendMsg), m)
}

// RecvMsg mocks base method
func (m_2 *MockFairnodeService_SealConfirmClient) RecvMsg(m interface{}) error {
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockFairnodeService_SealConfirmClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockFairnodeService_SealConfirmClient)(nil).RecvMsg), m)
}

// MockFairnodeServiceServer is a mock of FairnodeServiceServer interface
type MockFairnodeServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockFairnodeServiceServerMockRecorder
}

// MockFairnodeServiceServerMockRecorder is the mock recorder for MockFairnodeServiceServer
type MockFairnodeServiceServerMockRecorder struct {
	mock *MockFairnodeServiceServer
}

// NewMockFairnodeServiceServer creates a new mock instance
func NewMockFairnodeServiceServer(ctrl *gomock.Controller) *MockFairnodeServiceServer {
	mock := &MockFairnodeServiceServer{ctrl: ctrl}
	mock.recorder = &MockFairnodeServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFairnodeServiceServer) EXPECT() *MockFairnodeServiceServerMockRecorder {
	return m.recorder
}

// HeartBeat mocks base method
func (m *MockFairnodeServiceServer) HeartBeat(arg0 context.Context, arg1 *common.HeartBeat) (*empty.Empty, error) {
	ret := m.ctrl.Call(m, "HeartBeat", arg0, arg1)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeartBeat indicates an expected call of HeartBeat
func (mr *MockFairnodeServiceServerMockRecorder) HeartBeat(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeartBeat", reflect.TypeOf((*MockFairnodeServiceServer)(nil).HeartBeat), arg0, arg1)
}

// RequestOtprn mocks base method
func (m *MockFairnodeServiceServer) RequestOtprn(arg0 context.Context, arg1 *common.ReqOtprn) (*common.ResOtprn, error) {
	ret := m.ctrl.Call(m, "RequestOtprn", arg0, arg1)
	ret0, _ := ret[0].(*common.ResOtprn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestOtprn indicates an expected call of RequestOtprn
func (mr *MockFairnodeServiceServerMockRecorder) RequestOtprn(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestOtprn", reflect.TypeOf((*MockFairnodeServiceServer)(nil).RequestOtprn), arg0, arg1)
}

// ProcessController mocks base method
func (m *MockFairnodeServiceServer) ProcessController(arg0 *common.Participate, arg1 fairnode.FairnodeService_ProcessControllerServer) error {
	ret := m.ctrl.Call(m, "ProcessController", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessController indicates an expected call of ProcessController
func (mr *MockFairnodeServiceServerMockRecorder) ProcessController(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessController", reflect.TypeOf((*MockFairnodeServiceServer)(nil).ProcessController), arg0, arg1)
}

// Vote mocks base method
func (m *MockFairnodeServiceServer) Vote(arg0 context.Context, arg1 *common.Vote) (*empty.Empty, error) {
	ret := m.ctrl.Call(m, "Vote", arg0, arg1)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Vote indicates an expected call of Vote
func (mr *MockFairnodeServiceServerMockRecorder) Vote(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vote", reflect.TypeOf((*MockFairnodeServiceServer)(nil).Vote), arg0, arg1)
}

// RequestVoteResult mocks base method
func (m *MockFairnodeServiceServer) RequestVoteResult(arg0 context.Context, arg1 *common.ReqVoteResult) (*common.ResVoteResult, error) {
	ret := m.ctrl.Call(m, "RequestVoteResult", arg0, arg1)
	ret0, _ := ret[0].(*common.ResVoteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestVoteResult indicates an expected call of RequestVoteResult
func (mr *MockFairnodeServiceServerMockRecorder) RequestVoteResult(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestVoteResult", reflect.TypeOf((*MockFairnodeServiceServer)(nil).RequestVoteResult), arg0, arg1)
}

// SealConfirm mocks base method
func (m *MockFairnodeServiceServer) SealConfirm(arg0 *common.ReqConfirmSeal, arg1 fairnode.FairnodeService_SealConfirmServer) error {
	ret := m.ctrl.Call(m, "SealConfirm", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SealConfirm indicates an expected call of SealConfirm
func (mr *MockFairnodeServiceServerMockRecorder) SealConfirm(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SealConfirm", reflect.TypeOf((*MockFairnodeServiceServer)(nil).SealConfirm), arg0, arg1)
}

// SendBlock mocks base method
func (m *MockFairnodeServiceServer) SendBlock(arg0 context.Context, arg1 *common.ReqBlock) (*empty.Empty, error) {
	ret := m.ctrl.Call(m, "SendBlock", arg0, arg1)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendBlock indicates an expected call of SendBlock
func (mr *MockFairnodeServiceServerMockRecorder) SendBlock(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBlock", reflect.TypeOf((*MockFairnodeServiceServer)(nil).SendBlock), arg0, arg1)
}

// RequestFairnodeSign mocks base method
func (m *MockFairnodeServiceServer) RequestFairnodeSign(arg0 context.Context, arg1 *common.ReqFairnodeSign) (*common.ResFairnodeSign, error) {
	ret := m.ctrl.Call(m, "RequestFairnodeSign", arg0, arg1)
	ret0, _ := ret[0].(*common.ResFairnodeSign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestFairnodeSign indicates an expected call of RequestFairnodeSign
func (mr *MockFairnodeServiceServerMockRecorder) RequestFairnodeSign(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestFairnodeSign", reflect.TypeOf((*MockFairnodeServiceServer)(nil).RequestFairnodeSign), arg0, arg1)
}

// MockFairnodeService_ProcessControllerServer is a mock of FairnodeService_ProcessControllerServer interface
type MockFairnodeService_ProcessControllerServer struct {
	ctrl     *gomock.Controller
	recorder *MockFairnodeService_ProcessControllerServerMockRecorder
}

// MockFairnodeService_ProcessControllerServerMockRecorder is the mock recorder for MockFairnodeService_ProcessControllerServer
type MockFairnodeService_ProcessControllerServerMockRecorder struct {
	mock *MockFairnodeService_ProcessControllerServer
}

// NewMockFairnodeService_ProcessControllerServer creates a new mock instance
func NewMockFairnodeService_ProcessControllerServer(ctrl *gomock.Controller) *MockFairnodeService_ProcessControllerServer {
	mock := &MockFairnodeService_ProcessControllerServer{ctrl: ctrl}
	mock.recorder = &MockFairnodeService_ProcessControllerServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFairnodeService_ProcessControllerServer) EXPECT() *MockFairnodeService_ProcessControllerServerMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockFairnodeService_ProcessControllerServer) Send(arg0 *common.ProcessMessage) error {
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockFairnodeService_ProcessControllerServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockFairnodeService_ProcessControllerServer)(nil).Send), arg0)
}

// SetHeader mocks base method
func (m *MockFairnodeService_ProcessControllerServer) SetHeader(arg0 metadata.MD) error {
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader
func (mr *MockFairnodeService_ProcessControllerServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockFairnodeService_ProcessControllerServer)(nil).SetHeader), arg0)
}

// SendHeader mocks base method
func (m *MockFairnodeService_ProcessControllerServer) SendHeader(arg0 metadata.MD) error {
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader
func (mr *MockFairnodeService_ProcessControllerServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockFairnodeService_ProcessControllerServer)(nil).SendHeader), arg0)
}

// SetTrailer mocks base method
func (m *MockFairnodeService_ProcessControllerServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer
func (mr *MockFairnodeService_ProcessControllerServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockFairnodeService_ProcessControllerServer)(nil).SetTrailer), arg0)
}

// Context mocks base method
func (m *MockFairnodeService_ProcessControllerServer) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockFairnodeService_ProcessControllerServerMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockFairnodeService_ProcessControllerServer)(nil).Context))
}

// SendMsg mocks base method
func (m_2 *MockFairnodeService_ProcessControllerServer) SendMsg(m interface{}) error {
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockFairnodeService_ProcessControllerServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockFairnodeService_ProcessControllerServer)(nil).SendMsg), m)
}

// RecvMsg mocks base method
func (m_2 *MockFairnodeService_ProcessControllerServer) RecvMsg(m interface{}) error {
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockFairnodeService_ProcessControllerServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockFairnodeService_ProcessControllerServer)(nil).RecvMsg), m)
}

// MockFairnodeService_SealConfirmServer is a mock of FairnodeService_SealConfirmServer interface
type MockFairnodeService_SealConfirmServer struct {
	ctrl     *gomock.Controller
	recorder *MockFairnodeService_SealConfirmServerMockRecorder
}

// MockFairnodeService_SealConfirmServerMockRecorder is the mock recorder for MockFairnodeService_SealConfirmServer
type MockFairnodeService_SealConfirmServerMockRecorder struct {
	mock *MockFairnodeService_SealConfirmServer
}

// NewMockFairnodeService_SealConfirmServer creates a new mock instance
func NewMockFairnodeService_SealConfirmServer(ctrl *gomock.Controller) *MockFairnodeService_SealConfirmServer {
	mock := &MockFairnodeService_SealConfirmServer{ctrl: ctrl}
	mock.recorder = &MockFairnodeService_SealConfirmServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFairnodeService_SealConfirmServer) EXPECT() *MockFairnodeService_SealConfirmServerMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockFairnodeService_SealConfirmServer) Send(arg0 *common.ResConfirmSeal) error {
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockFairnodeService_SealConfirmServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockFairnodeService_SealConfirmServer)(nil).Send), arg0)
}

// SetHeader mocks base method
func (m *MockFairnodeService_SealConfirmServer) SetHeader(arg0 metadata.MD) error {
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader
func (mr *MockFairnodeService_SealConfirmServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockFairnodeService_SealConfirmServer)(nil).SetHeader), arg0)
}

// SendHeader mocks base method
func (m *MockFairnodeService_SealConfirmServer) SendHeader(arg0 metadata.MD) error {
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader
func (mr *MockFairnodeService_SealConfirmServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockFairnodeService_SealConfirmServer)(nil).SendHeader), arg0)
}

// SetTrailer mocks base method
func (m *MockFairnodeService_SealConfirmServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer
func (mr *MockFairnodeService_SealConfirmServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockFairnodeService_SealConfirmServer)(nil).SetTrailer), arg0)
}

// Context mocks base method
func (m *MockFairnodeService_SealConfirmServer) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockFairnodeService_SealConfirmServerMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockFairnodeService_SealConfirmServer)(nil).Context))
}

// SendMsg mocks base method
func (m_2 *MockFairnodeService_SealConfirmServer) SendMsg(m interface{}) error {
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockFairnodeService_SealConfirmServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockFairnodeService_SealConfirmServer)(nil).SendMsg), m)
}

// RecvMsg mocks base method
func (m_2 *MockFairnodeService_SealConfirmServer) RecvMsg(m interface{}) error {
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockFairnodeService_SealConfirmServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockFairnodeService_SealConfirmServer)(nil).RecvMsg), m)
}
