// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SampleMessage struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleMessage) Reset()         { *m = SampleMessage{} }
func (m *SampleMessage) String() string { return proto.CompactTextString(m) }
func (*SampleMessage) ProtoMessage()    {}
func (*SampleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *SampleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleMessage.Unmarshal(m, b)
}
func (m *SampleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleMessage.Marshal(b, m, deterministic)
}
func (m *SampleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleMessage.Merge(m, src)
}
func (m *SampleMessage) XXX_Size() int {
	return xxx_messageInfo_SampleMessage.Size(m)
}
func (m *SampleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SampleMessage proto.InternalMessageInfo

func (m *SampleMessage) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SampleMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SampleMessage)(nil), "common.SampleMessage")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6) }

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x2d, 0x17, 0x6f, 0x70, 0x62, 0x6e, 0x41, 0x4e, 0xaa, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa,
	0x90, 0x10, 0x17, 0x4b, 0x72, 0x7e, 0x4a, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x98,
	0x2d, 0x24, 0xc1, 0xc5, 0x9e, 0x0b, 0x91, 0x96, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x9d, 0x8c, 0xa3, 0x0c, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x13,
	0xf3, 0x52, 0x4a, 0x8b, 0x93, 0x33, 0x12, 0x33, 0xf3, 0xf4, 0xd3, 0xf3, 0x75, 0x91, 0x78, 0x60,
	0x3b, 0x8b, 0xa1, 0x2e, 0x48, 0x62, 0x03, 0x73, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0x78, 0x10, 0xdf, 0x99, 0x00, 0x00, 0x00,
}
