// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_SUCCESS Status = 0
	Status_FAIL    Status = 1
)

var Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}

var Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

type ProcessStatus int32

const (
	ProcessStatus_WAIT              ProcessStatus = 0
	ProcessStatus_MAKE_LEAGUE       ProcessStatus = 1
	ProcessStatus_MAKE_JOIN_TX      ProcessStatus = 2
	ProcessStatus_MAKE_BLOCK        ProcessStatus = 3
	ProcessStatus_VOTE_START        ProcessStatus = 4
	ProcessStatus_VOTE_COMPLETE     ProcessStatus = 5
	ProcessStatus_REJECT            ProcessStatus = 6
	ProcessStatus_SEND_BLOCK        ProcessStatus = 7
	ProcessStatus_SEND_BLOCK_WAIT   ProcessStatus = 8
	ProcessStatus_REQ_FAIRNODE_SIGN ProcessStatus = 9
	ProcessStatus_FINALIZE          ProcessStatus = 10
)

var ProcessStatus_name = map[int32]string{
	0:  "WAIT",
	1:  "MAKE_LEAGUE",
	2:  "MAKE_JOIN_TX",
	3:  "MAKE_BLOCK",
	4:  "VOTE_START",
	5:  "VOTE_COMPLETE",
	6:  "REJECT",
	7:  "SEND_BLOCK",
	8:  "SEND_BLOCK_WAIT",
	9:  "REQ_FAIRNODE_SIGN",
	10: "FINALIZE",
}

var ProcessStatus_value = map[string]int32{
	"WAIT":              0,
	"MAKE_LEAGUE":       1,
	"MAKE_JOIN_TX":      2,
	"MAKE_BLOCK":        3,
	"VOTE_START":        4,
	"VOTE_COMPLETE":     5,
	"REJECT":            6,
	"SEND_BLOCK":        7,
	"SEND_BLOCK_WAIT":   8,
	"REQ_FAIRNODE_SIGN": 9,
	"FINALIZE":          10,
}

func (x ProcessStatus) String() string {
	return proto.EnumName(ProcessStatus_name, int32(x))
}

func (ProcessStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

type HeartBeat struct {
	Enode                string   `protobuf:"bytes,1,opt,name=enode,proto3" json:"enode,omitempty"`
	MinerAddress         string   `protobuf:"bytes,2,opt,name=minerAddress,proto3" json:"minerAddress,omitempty"`
	ChainID              string   `protobuf:"bytes,3,opt,name=chainID,proto3" json:"chainID,omitempty"`
	NodeVersion          string   `protobuf:"bytes,4,opt,name=nodeVersion,proto3" json:"nodeVersion,omitempty"`
	Head                 string   `protobuf:"bytes,5,opt,name=head,proto3" json:"head,omitempty"`
	Port                 int64    `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Sign                 []byte   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (m *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(m, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

func (m *HeartBeat) GetEnode() string {
	if m != nil {
		return m.Enode
	}
	return ""
}

func (m *HeartBeat) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *HeartBeat) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *HeartBeat) GetNodeVersion() string {
	if m != nil {
		return m.NodeVersion
	}
	return ""
}

func (m *HeartBeat) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *HeartBeat) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *HeartBeat) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type Participate struct {
	OtprnHash            []byte   `protobuf:"bytes,1,opt,name=otprnHash,proto3" json:"otprnHash,omitempty"`
	Enode                string   `protobuf:"bytes,2,opt,name=enode,proto3" json:"enode,omitempty"`
	MinerAddress         string   `protobuf:"bytes,3,opt,name=minerAddress,proto3" json:"minerAddress,omitempty"`
	Sign                 []byte   `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Participate) Reset()         { *m = Participate{} }
func (m *Participate) String() string { return proto.CompactTextString(m) }
func (*Participate) ProtoMessage()    {}
func (*Participate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *Participate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Participate.Unmarshal(m, b)
}
func (m *Participate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Participate.Marshal(b, m, deterministic)
}
func (m *Participate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participate.Merge(m, src)
}
func (m *Participate) XXX_Size() int {
	return xxx_messageInfo_Participate.Size(m)
}
func (m *Participate) XXX_DiscardUnknown() {
	xxx_messageInfo_Participate.DiscardUnknown(m)
}

var xxx_messageInfo_Participate proto.InternalMessageInfo

func (m *Participate) GetOtprnHash() []byte {
	if m != nil {
		return m.OtprnHash
	}
	return nil
}

func (m *Participate) GetEnode() string {
	if m != nil {
		return m.Enode
	}
	return ""
}

func (m *Participate) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *Participate) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ProcessMessage struct {
	Code                 ProcessStatus `protobuf:"varint,1,opt,name=code,proto3,enum=common.ProcessStatus" json:"code,omitempty"`
	CurrentBlockNum      []byte        `protobuf:"bytes,2,opt,name=currentBlockNum,proto3" json:"currentBlockNum,omitempty"`
	Sign                 []byte        `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProcessMessage) Reset()         { *m = ProcessMessage{} }
func (m *ProcessMessage) String() string { return proto.CompactTextString(m) }
func (*ProcessMessage) ProtoMessage()    {}
func (*ProcessMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{2}
}

func (m *ProcessMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessMessage.Unmarshal(m, b)
}
func (m *ProcessMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessMessage.Marshal(b, m, deterministic)
}
func (m *ProcessMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessMessage.Merge(m, src)
}
func (m *ProcessMessage) XXX_Size() int {
	return xxx_messageInfo_ProcessMessage.Size(m)
}
func (m *ProcessMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessMessage proto.InternalMessageInfo

func (m *ProcessMessage) GetCode() ProcessStatus {
	if m != nil {
		return m.Code
	}
	return ProcessStatus_WAIT
}

func (m *ProcessMessage) GetCurrentBlockNum() []byte {
	if m != nil {
		return m.CurrentBlockNum
	}
	return nil
}

func (m *ProcessMessage) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// OTRPN 요청
type ReqOtprn struct {
	Enode                string   `protobuf:"bytes,1,opt,name=enode,proto3" json:"enode,omitempty"`
	MinerAddress         string   `protobuf:"bytes,2,opt,name=minerAddress,proto3" json:"minerAddress,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqOtprn) Reset()         { *m = ReqOtprn{} }
func (m *ReqOtprn) String() string { return proto.CompactTextString(m) }
func (*ReqOtprn) ProtoMessage()    {}
func (*ReqOtprn) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{3}
}

func (m *ReqOtprn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqOtprn.Unmarshal(m, b)
}
func (m *ReqOtprn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqOtprn.Marshal(b, m, deterministic)
}
func (m *ReqOtprn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqOtprn.Merge(m, src)
}
func (m *ReqOtprn) XXX_Size() int {
	return xxx_messageInfo_ReqOtprn.Size(m)
}
func (m *ReqOtprn) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqOtprn.DiscardUnknown(m)
}

var xxx_messageInfo_ReqOtprn proto.InternalMessageInfo

func (m *ReqOtprn) GetEnode() string {
	if m != nil {
		return m.Enode
	}
	return ""
}

func (m *ReqOtprn) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *ReqOtprn) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ResOtprn struct {
	Result               Status   `protobuf:"varint,1,opt,name=result,proto3,enum=common.Status" json:"result,omitempty"`
	Otprn                []byte   `protobuf:"bytes,2,opt,name=otprn,proto3" json:"otprn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResOtprn) Reset()         { *m = ResOtprn{} }
func (m *ResOtprn) String() string { return proto.CompactTextString(m) }
func (*ResOtprn) ProtoMessage()    {}
func (*ResOtprn) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{4}
}

func (m *ResOtprn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResOtprn.Unmarshal(m, b)
}
func (m *ResOtprn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResOtprn.Marshal(b, m, deterministic)
}
func (m *ResOtprn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResOtprn.Merge(m, src)
}
func (m *ResOtprn) XXX_Size() int {
	return xxx_messageInfo_ResOtprn.Size(m)
}
func (m *ResOtprn) XXX_DiscardUnknown() {
	xxx_messageInfo_ResOtprn.DiscardUnknown(m)
}

var xxx_messageInfo_ResOtprn proto.InternalMessageInfo

func (m *ResOtprn) GetResult() Status {
	if m != nil {
		return m.Result
	}
	return Status_SUCCESS
}

func (m *ResOtprn) GetOtprn() []byte {
	if m != nil {
		return m.Otprn
	}
	return nil
}

// 리그 요청
type ReqLeague struct {
	OtprnHash            []byte   `protobuf:"bytes,1,opt,name=otprnHash,proto3" json:"otprnHash,omitempty"`
	Enode                string   `protobuf:"bytes,2,opt,name=enode,proto3" json:"enode,omitempty"`
	MinerAddress         string   `protobuf:"bytes,3,opt,name=minerAddress,proto3" json:"minerAddress,omitempty"`
	Sign                 []byte   `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLeague) Reset()         { *m = ReqLeague{} }
func (m *ReqLeague) String() string { return proto.CompactTextString(m) }
func (*ReqLeague) ProtoMessage()    {}
func (*ReqLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{5}
}

func (m *ReqLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLeague.Unmarshal(m, b)
}
func (m *ReqLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLeague.Marshal(b, m, deterministic)
}
func (m *ReqLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLeague.Merge(m, src)
}
func (m *ReqLeague) XXX_Size() int {
	return xxx_messageInfo_ReqLeague.Size(m)
}
func (m *ReqLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLeague.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLeague proto.InternalMessageInfo

func (m *ReqLeague) GetOtprnHash() []byte {
	if m != nil {
		return m.OtprnHash
	}
	return nil
}

func (m *ReqLeague) GetEnode() string {
	if m != nil {
		return m.Enode
	}
	return ""
}

func (m *ReqLeague) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *ReqLeague) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ResLeague struct {
	Result               Status   `protobuf:"varint,1,opt,name=result,proto3,enum=common.Status" json:"result,omitempty"`
	Enodes               []string `protobuf:"bytes,2,rep,name=enodes,proto3" json:"enodes,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResLeague) Reset()         { *m = ResLeague{} }
func (m *ResLeague) String() string { return proto.CompactTextString(m) }
func (*ResLeague) ProtoMessage()    {}
func (*ResLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{6}
}

func (m *ResLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResLeague.Unmarshal(m, b)
}
func (m *ResLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResLeague.Marshal(b, m, deterministic)
}
func (m *ResLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResLeague.Merge(m, src)
}
func (m *ResLeague) XXX_Size() int {
	return xxx_messageInfo_ResLeague.Size(m)
}
func (m *ResLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_ResLeague.DiscardUnknown(m)
}

var xxx_messageInfo_ResLeague proto.InternalMessageInfo

func (m *ResLeague) GetResult() Status {
	if m != nil {
		return m.Result
	}
	return Status_SUCCESS
}

func (m *ResLeague) GetEnodes() []string {
	if m != nil {
		return m.Enodes
	}
	return nil
}

func (m *ResLeague) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 투표
type Vote struct {
	Header               []byte   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	VoterAddress         string   `protobuf:"bytes,2,opt,name=voterAddress,proto3" json:"voterAddress,omitempty"`
	VoterSign            []byte   `protobuf:"bytes,3,opt,name=voterSign,proto3" json:"voterSign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{7}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Vote) GetVoterAddress() string {
	if m != nil {
		return m.VoterAddress
	}
	return ""
}

func (m *Vote) GetVoterSign() []byte {
	if m != nil {
		return m.VoterSign
	}
	return nil
}

// 투표 결과 요청
type ReqVoteResult struct {
	OtprnHash            []byte   `protobuf:"bytes,1,opt,name=otprnHash,proto3" json:"otprnHash,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqVoteResult) Reset()         { *m = ReqVoteResult{} }
func (m *ReqVoteResult) String() string { return proto.CompactTextString(m) }
func (*ReqVoteResult) ProtoMessage()    {}
func (*ReqVoteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{8}
}

func (m *ReqVoteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqVoteResult.Unmarshal(m, b)
}
func (m *ReqVoteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqVoteResult.Marshal(b, m, deterministic)
}
func (m *ReqVoteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqVoteResult.Merge(m, src)
}
func (m *ReqVoteResult) XXX_Size() int {
	return xxx_messageInfo_ReqVoteResult.Size(m)
}
func (m *ReqVoteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqVoteResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReqVoteResult proto.InternalMessageInfo

func (m *ReqVoteResult) GetOtprnHash() []byte {
	if m != nil {
		return m.OtprnHash
	}
	return nil
}

func (m *ReqVoteResult) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReqVoteResult) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ResVoteResult struct {
	Result               Status   `protobuf:"varint,1,opt,name=result,proto3,enum=common.Status" json:"result,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Voters               []*Vote  `protobuf:"bytes,3,rep,name=voters,proto3" json:"voters,omitempty"`
	Sign                 []byte   `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResVoteResult) Reset()         { *m = ResVoteResult{} }
func (m *ResVoteResult) String() string { return proto.CompactTextString(m) }
func (*ResVoteResult) ProtoMessage()    {}
func (*ResVoteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{9}
}

func (m *ResVoteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResVoteResult.Unmarshal(m, b)
}
func (m *ResVoteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResVoteResult.Marshal(b, m, deterministic)
}
func (m *ResVoteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResVoteResult.Merge(m, src)
}
func (m *ResVoteResult) XXX_Size() int {
	return xxx_messageInfo_ResVoteResult.Size(m)
}
func (m *ResVoteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ResVoteResult.DiscardUnknown(m)
}

var xxx_messageInfo_ResVoteResult proto.InternalMessageInfo

func (m *ResVoteResult) GetResult() Status {
	if m != nil {
		return m.Result
	}
	return Status_SUCCESS
}

func (m *ResVoteResult) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *ResVoteResult) GetVoters() []*Vote {
	if m != nil {
		return m.Voters
	}
	return nil
}

func (m *ResVoteResult) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 블록 실링 확인 요청
type ReqConfirmSeal struct {
	OtprnHash            []byte   `protobuf:"bytes,1,opt,name=otprnHash,proto3" json:"otprnHash,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	VoteHash             []byte   `protobuf:"bytes,3,opt,name=voteHash,proto3" json:"voteHash,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Sign                 []byte   `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqConfirmSeal) Reset()         { *m = ReqConfirmSeal{} }
func (m *ReqConfirmSeal) String() string { return proto.CompactTextString(m) }
func (*ReqConfirmSeal) ProtoMessage()    {}
func (*ReqConfirmSeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{10}
}

func (m *ReqConfirmSeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqConfirmSeal.Unmarshal(m, b)
}
func (m *ReqConfirmSeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqConfirmSeal.Marshal(b, m, deterministic)
}
func (m *ReqConfirmSeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqConfirmSeal.Merge(m, src)
}
func (m *ReqConfirmSeal) XXX_Size() int {
	return xxx_messageInfo_ReqConfirmSeal.Size(m)
}
func (m *ReqConfirmSeal) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqConfirmSeal.DiscardUnknown(m)
}

var xxx_messageInfo_ReqConfirmSeal proto.InternalMessageInfo

func (m *ReqConfirmSeal) GetOtprnHash() []byte {
	if m != nil {
		return m.OtprnHash
	}
	return nil
}

func (m *ReqConfirmSeal) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *ReqConfirmSeal) GetVoteHash() []byte {
	if m != nil {
		return m.VoteHash
	}
	return nil
}

func (m *ReqConfirmSeal) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReqConfirmSeal) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ResConfirmSeal struct {
	Code                 ProcessStatus `protobuf:"varint,1,opt,name=code,proto3,enum=common.ProcessStatus" json:"code,omitempty"`
	Sign                 []byte        `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResConfirmSeal) Reset()         { *m = ResConfirmSeal{} }
func (m *ResConfirmSeal) String() string { return proto.CompactTextString(m) }
func (*ResConfirmSeal) ProtoMessage()    {}
func (*ResConfirmSeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{11}
}

func (m *ResConfirmSeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResConfirmSeal.Unmarshal(m, b)
}
func (m *ResConfirmSeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResConfirmSeal.Marshal(b, m, deterministic)
}
func (m *ResConfirmSeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResConfirmSeal.Merge(m, src)
}
func (m *ResConfirmSeal) XXX_Size() int {
	return xxx_messageInfo_ResConfirmSeal.Size(m)
}
func (m *ResConfirmSeal) XXX_DiscardUnknown() {
	xxx_messageInfo_ResConfirmSeal.DiscardUnknown(m)
}

var xxx_messageInfo_ResConfirmSeal proto.InternalMessageInfo

func (m *ResConfirmSeal) GetCode() ProcessStatus {
	if m != nil {
		return m.Code
	}
	return ProcessStatus_WAIT
}

func (m *ResConfirmSeal) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 블록 요청
type ReqBlock struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBlock) Reset()         { *m = ReqBlock{} }
func (m *ReqBlock) String() string { return proto.CompactTextString(m) }
func (*ReqBlock) ProtoMessage()    {}
func (*ReqBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{12}
}

func (m *ReqBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBlock.Unmarshal(m, b)
}
func (m *ReqBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBlock.Marshal(b, m, deterministic)
}
func (m *ReqBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBlock.Merge(m, src)
}
func (m *ReqBlock) XXX_Size() int {
	return xxx_messageInfo_ReqBlock.Size(m)
}
func (m *ReqBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBlock proto.InternalMessageInfo

func (m *ReqBlock) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *ReqBlock) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReqBlock) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 블록 서명 요청
type ReqFairnodeSign struct {
	OtprnHash            []byte   `protobuf:"bytes,1,opt,name=otprnHash,proto3" json:"otprnHash,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	VoteHash             []byte   `protobuf:"bytes,3,opt,name=voteHash,proto3" json:"voteHash,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Sign                 []byte   `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqFairnodeSign) Reset()         { *m = ReqFairnodeSign{} }
func (m *ReqFairnodeSign) String() string { return proto.CompactTextString(m) }
func (*ReqFairnodeSign) ProtoMessage()    {}
func (*ReqFairnodeSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{13}
}

func (m *ReqFairnodeSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqFairnodeSign.Unmarshal(m, b)
}
func (m *ReqFairnodeSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqFairnodeSign.Marshal(b, m, deterministic)
}
func (m *ReqFairnodeSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqFairnodeSign.Merge(m, src)
}
func (m *ReqFairnodeSign) XXX_Size() int {
	return xxx_messageInfo_ReqFairnodeSign.Size(m)
}
func (m *ReqFairnodeSign) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqFairnodeSign.DiscardUnknown(m)
}

var xxx_messageInfo_ReqFairnodeSign proto.InternalMessageInfo

func (m *ReqFairnodeSign) GetOtprnHash() []byte {
	if m != nil {
		return m.OtprnHash
	}
	return nil
}

func (m *ReqFairnodeSign) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *ReqFairnodeSign) GetVoteHash() []byte {
	if m != nil {
		return m.VoteHash
	}
	return nil
}

func (m *ReqFairnodeSign) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReqFairnodeSign) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ResFairnodeSign struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Sign                 []byte   `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResFairnodeSign) Reset()         { *m = ResFairnodeSign{} }
func (m *ResFairnodeSign) String() string { return proto.CompactTextString(m) }
func (*ResFairnodeSign) ProtoMessage()    {}
func (*ResFairnodeSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{14}
}

func (m *ResFairnodeSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResFairnodeSign.Unmarshal(m, b)
}
func (m *ResFairnodeSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResFairnodeSign.Marshal(b, m, deterministic)
}
func (m *ResFairnodeSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResFairnodeSign.Merge(m, src)
}
func (m *ResFairnodeSign) XXX_Size() int {
	return xxx_messageInfo_ResFairnodeSign.Size(m)
}
func (m *ResFairnodeSign) XXX_DiscardUnknown() {
	xxx_messageInfo_ResFairnodeSign.DiscardUnknown(m)
}

var xxx_messageInfo_ResFairnodeSign proto.InternalMessageInfo

func (m *ResFairnodeSign) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ResFairnodeSign) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterEnum("common.Status", Status_name, Status_value)
	proto.RegisterEnum("common.ProcessStatus", ProcessStatus_name, ProcessStatus_value)
	proto.RegisterType((*HeartBeat)(nil), "common.HeartBeat")
	proto.RegisterType((*Participate)(nil), "common.Participate")
	proto.RegisterType((*ProcessMessage)(nil), "common.ProcessMessage")
	proto.RegisterType((*ReqOtprn)(nil), "common.ReqOtprn")
	proto.RegisterType((*ResOtprn)(nil), "common.ResOtprn")
	proto.RegisterType((*ReqLeague)(nil), "common.ReqLeague")
	proto.RegisterType((*ResLeague)(nil), "common.ResLeague")
	proto.RegisterType((*Vote)(nil), "common.Vote")
	proto.RegisterType((*ReqVoteResult)(nil), "common.ReqVoteResult")
	proto.RegisterType((*ResVoteResult)(nil), "common.ResVoteResult")
	proto.RegisterType((*ReqConfirmSeal)(nil), "common.ReqConfirmSeal")
	proto.RegisterType((*ResConfirmSeal)(nil), "common.ResConfirmSeal")
	proto.RegisterType((*ReqBlock)(nil), "common.ReqBlock")
	proto.RegisterType((*ReqFairnodeSign)(nil), "common.ReqFairnodeSign")
	proto.RegisterType((*ResFairnodeSign)(nil), "common.ResFairnodeSign")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6) }

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 757 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x6f, 0x4f, 0xda, 0x40,
	0x18, 0xb7, 0x50, 0x0a, 0x3c, 0x54, 0xa8, 0xe7, 0x5c, 0x9a, 0xc5, 0x64, 0x84, 0x2c, 0x0b, 0x33,
	0x99, 0x66, 0xfa, 0x09, 0x0a, 0x16, 0xad, 0x22, 0xb8, 0x2b, 0x3a, 0xe3, 0x5e, 0xb0, 0x0a, 0x37,
	0x68, 0x26, 0x2d, 0xdc, 0xb5, 0x5b, 0xf6, 0x29, 0xf6, 0x6e, 0xfb, 0x34, 0x7b, 0xb9, 0xef, 0xb5,
	0xdc, 0xb5, 0x95, 0xa2, 0xc4, 0x69, 0x96, 0x2c, 0x7b, 0x45, 0x7f, 0xcf, 0x53, 0x9e, 0xdf, 0x9f,
	0x7b, 0x9a, 0x83, 0xf5, 0x81, 0x3f, 0x99, 0xf8, 0xde, 0x4e, 0xf4, 0xb3, 0x3d, 0xa5, 0x7e, 0xe0,
	0x23, 0x25, 0x42, 0xb5, 0x9f, 0x12, 0x14, 0x0f, 0x89, 0x43, 0x83, 0x06, 0x71, 0x02, 0xf4, 0x04,
	0x72, 0xc4, 0xf3, 0x87, 0x44, 0x97, 0xaa, 0x52, 0xbd, 0x88, 0x23, 0x80, 0x6a, 0xa0, 0x4e, 0x5c,
	0x8f, 0x50, 0x63, 0x38, 0xa4, 0x84, 0x31, 0x3d, 0x23, 0x9a, 0x0b, 0x35, 0xa4, 0x43, 0x7e, 0x30,
	0x76, 0x5c, 0xcf, 0xda, 0xd7, 0xb3, 0xa2, 0x9d, 0x40, 0x54, 0x85, 0x12, 0x9f, 0x72, 0x4e, 0x28,
	0x73, 0x7d, 0x4f, 0x97, 0x45, 0x37, 0x5d, 0x42, 0x08, 0xe4, 0x31, 0x71, 0x86, 0x7a, 0x4e, 0xb4,
	0xc4, 0x33, 0xaf, 0x4d, 0x7d, 0x1a, 0xe8, 0x4a, 0x55, 0xaa, 0x67, 0xb1, 0x78, 0xe6, 0x35, 0xe6,
	0x8e, 0x3c, 0x3d, 0x5f, 0x95, 0xea, 0x2a, 0x16, 0xcf, 0xb5, 0xaf, 0x50, 0x3a, 0x75, 0x68, 0xe0,
	0x0e, 0xdc, 0xa9, 0x13, 0x10, 0xb4, 0x09, 0x45, 0x3f, 0x98, 0x52, 0xef, 0xd0, 0x61, 0x63, 0x61,
	0x42, 0xc5, 0xf3, 0xc2, 0xdc, 0x5e, 0xe6, 0x3e, 0x7b, 0xd9, 0x25, 0xf6, 0x12, 0x6a, 0x79, 0x81,
	0xba, 0x7c, 0x4a, 0xfd, 0x01, 0x61, 0xec, 0x84, 0x30, 0xe6, 0x8c, 0x08, 0x7a, 0x05, 0xf2, 0x20,
	0x49, 0xaf, 0xbc, 0xbb, 0xb1, 0x1d, 0x27, 0x1e, 0xbf, 0x65, 0x07, 0x4e, 0x10, 0x32, 0x2c, 0x5e,
	0x41, 0x75, 0xa8, 0x0c, 0x42, 0x4a, 0x89, 0x17, 0x34, 0xae, 0xfd, 0xc1, 0xa7, 0x4e, 0x38, 0x11,
	0xa2, 0x54, 0x7c, 0xbb, 0x7c, 0x43, 0x9d, 0x4d, 0x51, 0x5f, 0x40, 0x01, 0x93, 0x59, 0x97, 0x1b,
	0xfb, 0x8b, 0x33, 0x5b, 0x36, 0xf9, 0x90, 0x4f, 0x66, 0xd1, 0xe4, 0x97, 0xa0, 0x50, 0xc2, 0xc2,
	0xeb, 0x20, 0x36, 0x54, 0x4e, 0x0c, 0xc5, 0x4e, 0xe2, 0x2e, 0x57, 0x20, 0x32, 0x8e, 0x1d, 0x44,
	0xa0, 0xf6, 0x05, 0x8a, 0x98, 0xcc, 0xda, 0xc4, 0x19, 0x85, 0xff, 0xf6, 0x5c, 0xfa, 0x9c, 0x98,
	0xc5, 0xc4, 0x0f, 0xf5, 0xf0, 0x14, 0x14, 0xc1, 0xca, 0x93, 0xca, 0xd6, 0x8b, 0x38, 0x46, 0x4b,
	0x33, 0xfa, 0x00, 0xf2, 0xb9, 0x1f, 0x10, 0xfe, 0x1f, 0xbe, 0xab, 0x84, 0xc6, 0x8e, 0x62, 0xc4,
	0x85, 0x7f, 0xf6, 0x83, 0x3b, 0xd9, 0xa7, 0x6b, 0x3c, 0x10, 0x81, 0xed, 0xf9, 0xf0, 0x79, 0xa1,
	0xf6, 0x1e, 0x56, 0x31, 0x99, 0x71, 0x12, 0x1c, 0xc9, 0xbb, 0x3f, 0x3f, 0x1d, 0xf2, 0xce, 0x02,
	0x57, 0x02, 0x97, 0xca, 0xff, 0x26, 0xf1, 0xe9, 0x2c, 0x35, 0xfd, 0xa1, 0x21, 0x6d, 0x42, 0xf1,
	0x8a, 0xaf, 0xa5, 0x50, 0x11, 0x31, 0xcd, 0x0b, 0xe8, 0x05, 0x28, 0xc2, 0x01, 0x3f, 0xa9, 0x6c,
	0xbd, 0xb4, 0xab, 0x26, 0x53, 0x04, 0x53, 0xdc, 0x5b, 0x7a, 0x62, 0xdf, 0x25, 0x28, 0x63, 0x32,
	0x6b, 0xfa, 0xde, 0x47, 0x97, 0x4e, 0x6c, 0xe2, 0x5c, 0xff, 0xc1, 0xf0, 0x1d, 0x21, 0x6a, 0x5a,
	0xc8, 0x33, 0x28, 0x70, 0x32, 0xd1, 0x8c, 0x8c, 0xdf, 0xe0, 0x74, 0x54, 0xf2, 0xf2, 0xa8, 0x72,
	0x29, 0x61, 0x5d, 0xae, 0x8b, 0xa5, 0x75, 0x3d, 0xe2, 0x13, 0x4f, 0x06, 0x66, 0x52, 0x03, 0x3b,
	0xe2, 0xc3, 0x15, 0xdf, 0x36, 0xdf, 0x7a, 0xa1, 0x39, 0xb6, 0x17, 0x81, 0x47, 0x9e, 0xe5, 0x0f,
	0x09, 0x2a, 0x98, 0xcc, 0x5a, 0x8e, 0x4b, 0xf9, 0xbe, 0xf2, 0xe5, 0xf9, 0x4f, 0xa2, 0x6b, 0x72,
	0x61, 0xec, 0xb6, 0x30, 0xde, 0x72, 0x82, 0x90, 0x92, 0x44, 0xd8, 0x4d, 0x61, 0x59, 0x5c, 0x5b,
	0xcf, 0x41, 0x89, 0x22, 0x45, 0x25, 0xc8, 0xdb, 0x67, 0xcd, 0xa6, 0x69, 0xdb, 0xda, 0x0a, 0x2a,
	0x80, 0xdc, 0x32, 0xac, 0xb6, 0x26, 0x6d, 0xfd, 0x92, 0x60, 0x75, 0x21, 0x7b, 0xde, 0x7b, 0x67,
	0x58, 0x3d, 0x6d, 0x05, 0x55, 0xa0, 0x74, 0x62, 0x1c, 0x9b, 0xfd, 0xb6, 0x69, 0x1c, 0x9c, 0x99,
	0x9a, 0x84, 0x34, 0x50, 0x45, 0xe1, 0xa8, 0x6b, 0x75, 0xfa, 0xbd, 0x0b, 0x2d, 0x83, 0xca, 0x00,
	0xa2, 0xd2, 0x68, 0x77, 0x9b, 0xc7, 0x5a, 0x96, 0xe3, 0xf3, 0x6e, 0xcf, 0xec, 0xdb, 0x3d, 0x03,
	0xf7, 0x34, 0x19, 0xad, 0xc1, 0xaa, 0xc0, 0xcd, 0xee, 0xc9, 0x69, 0xdb, 0xec, 0x99, 0x5a, 0x0e,
	0x01, 0x28, 0xd8, 0x3c, 0x32, 0x9b, 0x3d, 0x4d, 0xe1, 0xaf, 0xdb, 0x66, 0x67, 0x3f, 0xfe, 0x7b,
	0x1e, 0xad, 0x43, 0x65, 0x8e, 0xfb, 0x42, 0x46, 0x01, 0x6d, 0xc0, 0x1a, 0x36, 0xdf, 0xf6, 0x5b,
	0x86, 0x85, 0x3b, 0xdd, 0x7d, 0xb3, 0x6f, 0x5b, 0x07, 0x1d, 0xad, 0x88, 0x54, 0x28, 0xb4, 0xac,
	0x8e, 0xd1, 0xb6, 0x2e, 0x4d, 0x0d, 0x1a, 0x7b, 0x97, 0x6f, 0x46, 0x6e, 0x30, 0x0e, 0xaf, 0xf8,
	0x42, 0xed, 0x38, 0xde, 0x30, 0x64, 0xe2, 0xfe, 0xdc, 0x19, 0xf9, 0xaf, 0x53, 0x48, 0xdc, 0xdd,
	0x2c, 0xbe, 0xc9, 0xaf, 0x14, 0x01, 0xf7, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xc2, 0x1c,
	0xbb, 0xe1, 0x07, 0x00, 0x00,
}
